chatgin:
  mysql:
    dsn: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local
  redis: 
    addr: 127.0.0.1:6379
    db: 0
    paasword: 123456
    poolSize: 10
    minIdleConns: 5